Add gitlab user to inline issue
kakawait/sonar-gitlab-plugin pull request #21
Opened 2017-03-03 13:52 UTC by dve

Add the gitlab userername with `@` to the inline comment, so the user gets their issues in the todo list

2017-03-03 20:01 UTC, kakawait commented
Thank for contribution. It's a good idea. I will review that during the weekend.

2017-03-06 12:48 UTC, kakawait requested changes
@dve Could you please use `space` indentation rather than `tab` like everywhere :)

Moreover I don't think everyone wants to be _pinged_ through `@` syntax. Could you please create a plugin configuration/option to be able to enable/disable feature?

2017-03-06 12:48 UTC, kakawait commented on src/main/java/com/synaptix/sonar/plugins/gitlab/GitLabApiFacade.java
> +			return username.orElse(null);
Why not returning `Optional<String>` directly rather than fallbacking on `null`

2017-03-06 14:49 UTC, dve commented on src/main/java/com/synaptix/sonar/plugins/gitlab/GitLabApiFacade.java
> +			return username.orElse(null);
@kakawait  I've pushed fixes

2017-03-06 14:52 UTC, kakawait commented
@dve And you wrote a unit tests! You rocks.

Can I merge it? Or you need to push something else?

2017-03-06 14:54 UTC, dve commented
@kakawait  you can merge

2017-03-06 14:54 UTC, kakawait approved these changes

2017-03-06 14:55 UTC, merged

2017-03-06 14:56 UTC, kakawait commented
I will release `1.10.0` at the end of the week, in order to add some more fixes/features.

2017-04-04 10:44 UTC, dve commented
Do you mind release `1.10.0`? Using self made builds is provoking questions ;-)

2017-04-04 10:56 UTC, kakawait commented
Oups I just forget sorry. I will do that

2017-04-07 06:44 UTC, kakawait commented
@dve Just pushed on github.